### ISSUE TITLE
GraalVM 20.3.0: ServiceLoader can not find JobOperator

### ISSUE THREAD

**Issue by ranlab** [quarkiverse/quarkiverse-jberet#12]
Hallo, 
I use quarkus-jberet 0.0.2 in a project with 10 splitting steps. All is running fine in any java package (fast-jar, ueber-jar). If I packaing this project native with graal I can see a Warning "The ServiceLoader was unable to find an implementation for JobOperator. Check classpath for META-INF/services/javax.batch.operations.JobOperator file." First instantiation of a JobOperator ends with a NullPointerException. What can I do?

**Comment by radcortez** [comment]
Let me have a look.

**Comment by ranlab** [comment]
Good morning,
excuse me for my badly english. I have create a new eclipse project. In
this I stripped all unnecessary code. There is a README.adoc in project
root. You need a local database. In project is a FlyWay configuration to
create database. Then you can execute it with "mvn
--settings=./settings.xml *-Dquarkus-profile=ranlab* clean compile
quarkus:dev" and call endpoint "curl -XGET
http://localhost:8080/batch/launch/M101". It should create a file in /tmp
as an export from one table.
In JVM mode is all fine. If you do the same things in native mode you will
et an Nullpointer exception.

Project file is in my drive and I released it for you.

I hope all is running and you will find my mistake
R. Andrae


Am Di., 5. Jan. 2021 um 17:04 Uhr schrieb Roberto Cortez <
notifications@github.com>:

**Comment by radcortez** [comment]
No worries. Thanks for the reproducer. I was also able to reproduce it myself with an integration test. I've opened a PR that should fix the issue. Are you able to try it before I do a release? Thanks!

**Comment by radcortez** [comment]
@ranlab did you had a look into my fix? Can I release a new version?

**Comment by ranlab** [comment]
Good Morning Roberto,
I checked out your Snapshot and tested it. Now its working perfect in
native mode. Please release the new version.

Have a nice day
Rüdiger Andrae

Am Mo., 11. Jan. 2021 um 18:22 Uhr schrieb Roberto Cortez <
notifications@github.com>:

**Comment by radcortez** [comment]
Thanks! I'll release today.

**Comment by radcortez** [comment]
@ranlab done! Just update the version :)

**Comment by ranlab** [comment]
Hallo,
I updated to version 0.0.3 and retested it. All is fine.

Thanks

Am Di., 12. Jan. 2021 um 14:39 Uhr schrieb Roberto Cortez <
notifications@github.com>:
